'''
This script converts the transaction CSV generated by Sharesies into a 
CSV readable by Simply Wall Street's Portfolio function.
'''

import pandas


def run():

    raw_df = get_dataframe()
    converted_df = convert_dataframe(raw_df)
    export_dataframe_to_csv(converted_df)

    print("CSV converted and saved to the same location as the original file.")


def get_dataframe():
    return False


def convert_dataframe():
    return False


def export_dataframe_to_csv():
    return False


if __name__ == "__main__":
    run()
