'''
This script converts the transaction CSV generated by Sharesies into a 
CSV readable by Simply Wall Street's Portfolio function.
'''

import pandas as pd
import os


def run():

    raw_df = get_dataframe()
    converted_df = convert_dataframe(raw_df)
    success = export_dataframe_to_csv(converted_df)

    if success:
        print("CSV converted and saved to the same location as the original file.")
    else:
        print("There was an error creating the new file.")


def get_dataframe():
    """Takes the path to the transaction-report.csv export from Sharesies
    and creates a Pandas Dataframe.

    Returns:
        pd.Dataframe: a Pandas Dataframe containing the data from Sharesies'
        transaction-report.csv export.
    """

    file_path = os.path.abspath(input("File path: ")).strip()
    df = pd.read_csv(file_path)
    return df


def convert_dataframe(raw_df):
    return False


def export_dataframe_to_csv(converted_df):
    return False


if __name__ == "__main__":
    run()
